# Documentos para la acción de implementación de Azure Web Apps: https://github.com/Azure/webapps-deploy
# Más acciones de GitHub para Azure: https://github.com/Azure/actions

name : compile e implemente la aplicación Node.js en Azure Web App - webauthntest

en :
  empujar :
    ramas :
      - maestro

trabajos :
  construir e implementar :
    se ejecuta : ubuntu-latest

    pasos :
    - usos : acciones / checkout @ master

    - nombre : configura la versión de Node.js
      usos : acciones / setup-node @ v1
      con :
        nodo-version : ' 12.x '

    - nombre : npm install, build y test
      ejecutar : |
        npm install
        npm ejecutar build --si-present
        prueba de ejecución npm --si-present
    - nombre : ' Implementar en la aplicación web de Azure '
      utiliza : azure / webapps-deploy @ v1
      con :
        nombre de la aplicación : ' webauthntest '
        nombre de ranura : ' producción '
        publicar-perfil : $ {{secrets.AzureAppService_PublishProfile_e19e0fa662fe473a9ce6c39415fcb1de}}
        empaquetar : .
